# Regression Exercise 

California Housing Data

This data set contains information about all the block groups in California from the 1990 Census. In this sample a block group on average includes 1425.5 individuals living in a geographically compact area. 

The task is to aproximate the median house value of each block from the values of the rest of the variables. 

 It has been obtained from the LIACC repository. The original page where the data set can be found is: http://www.liaad.up.pt/~ltorgo/Regression/DataSets.html.
 

The Features:
 
* housingMedianAge: continuous. 
* totalRooms: continuous. 
* totalBedrooms: continuous. 
* population: continuous. 
* households: continuous. 
* medianIncome: continuous. 
* medianHouseValue: continuous. 

## The Data

** Import the cal_housing_clean.csv file with pandas. Separate it into a training (70%) and testing set(30%).**

In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [18]:
housing = pd.read_csv('cal_housing_clean.csv')

In [20]:
housing.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
0              41.0       880.0          129.0       322.0       126.0   
1              21.0      7099.0         1106.0      2401.0      1138.0   
2              52.0      1467.0          190.0       496.0       177.0   
3              52.0      1274.0          235.0       558.0       219.0   
4              52.0      1627.0          280.0       565.0       259.0   

   medianIncome  medianHouseValue  
0        8.3252          452600.0  
1        8.3014          358500.0  
2        7.2574          352100.0  
3        5.6431          341300.0  
4        3.8462          342200.0

In [19]:
housing.describe()

housingMedianAge    totalRooms  totalBedrooms    population  \
count      20640.000000  20640.000000   20640.000000  20640.000000   
mean          28.639486   2635.763081     537.898014   1425.476744   
std           12.585558   2181.615252     421.247906   1132.462122   
min            1.000000      2.000000       1.000000      3.000000   
25%           18.000000   1447.750000     295.000000    787.000000   
50%           29.000000   2127.000000     435.000000   1166.000000   
75%           37.000000   3148.000000     647.000000   1725.000000   
max           52.000000  39320.000000    6445.000000  35682.000000   

         households  medianIncome  medianHouseValue  
count  20640.000000  20640.000000      20640.000000  
mean     499.539680      3.870671     206855.816909  
std      382.329753      1.899822     115395.615874  
min        1.000000      0.499900      14999.000000  
25%      280.000000      2.563400     119600.000000  
50%      409.000000      3.534800     179700.000000  
75%      605.000000      4.743250     264725.000000  
max     6082.000000     15.000100     500001.000000

In [47]:
x_data = housing.drop('medianHouseValue',axis=1)
labels = housing['medianHouseValue']
X_train, X_test, y_train, y_test = train_test_split(x_data,labels,test_size=0.3,
                                                    random_state=101)

### Scale the Feature Data

** Use sklearn preprocessing to create a MinMaxScaler for the feature data. Fit this scaler only to the training data. Then use it to transform X_test and X_train. Then use the scaled X_test and X_train along with pd.Dataframe to re-create two dataframes of scaled data.**

In [50]:
from sklearn.preprocessing import MinMaxScaler

In [51]:
scaler = MinMaxScaler()

In [52]:
X_train.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
6761              19.0      2742.0          756.0      1396.0       703.0   
3010              32.0       444.0          102.0       242.0        87.0   
7812              35.0       994.0          203.0       602.0       185.0   
8480              35.0      1281.0          219.0       710.0       184.0   
1051              16.0      1257.0          231.0       559.0       213.0   

      medianIncome  
6761        2.5663  
3010        1.1528  
7812        3.5865  
8480        4.8304  
1051        4.4531

In [53]:
print(scaler.fit(X_train))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [55]:
scaler.transform(X_train)  # This shows numpy arrary

array([[ -1.26874279e-02,  -4.90948628e-05,  -1.37001357e-04,
         -1.03323552e-04,  -1.45462664e-04,  -2.46473580e-02],
       [ -7.68935025e-03,  -5.05813706e-05,  -1.52750854e-04,
         -1.04738036e-04,  -1.62120965e-04,  -3.13701214e-02],
       [ -6.53594771e-03,  -5.02255920e-05,  -1.50318593e-04,
         -1.04296776e-04,  -1.59470781e-04,  -1.97951732e-02],
       ..., 
       [ -1.76855056e-02,  -4.85877166e-05,  -1.41745472e-04,
         -1.03345615e-04,  -1.51195716e-04,  -7.62047934e-03],
       [ -6.15148020e-03,  -5.03303850e-05,  -1.50125938e-04,
         -1.04366642e-04,  -1.58767671e-04,  -2.12467384e-02],
       [ -1.11495579e-02,  -4.86957439e-05,  -1.37747893e-04,
         -1.02752365e-04,  -1.46868884e-04,  -2.41451127e-02]])

In [54]:
X_train = pd.DataFrame(data=scaler.transform(X_train),
                       columns=X_train.columns,
                      index=X_train.index)

In [56]:
X_test = pd.DataFrame(data=scaler.transform(X_test),
                       columns=X_test.columns,
                      index=X_test.index)

### Create Feature Columns

** Create the necessary tf.feature_column objects for the estimator. They should all be trated as continuous numeric_columns. **

In [6]:
housing.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome', 'medianHouseValue'],
      dtype='object')

In [33]:
housingMedianAge = tf.feature_column.numeric_column('housingMedianAge')
totalRooms = tf.feature_column.numeric_column('totalRooms')
totalBedrooms = tf.feature_column.numeric_column('totalBedrooms')
population = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
medianIncome = tf.feature_column.numeric_column('medianIncome')
medianHouseValue = tf.feature_column.numeric_column('medianHouseValue')

In [34]:
feat_cols = [housingMedianAge, totalRooms, totalBedrooms, population,
       households, medianIncome]

** Create the input function for the estimator object. (play around with batch_size and num_epochs)**

In [36]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train, y=y_train, 
                                                 batch_size=10, 
                                                 num_epochs=1000,
                                                 shuffle=True)

** Create the estimator model. Use a DNNRegressor. Play around with the hidden units! **

In [39]:
dnn_model = tf.estimator.DNNRegressor(hidden_units = [10,10,10],
                                       feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_summary_steps': 100, '_model_dir': '/var/folders/s1/h9x0_mhx4tn1dfstx3w6gvhc0000gn/T/tmp0nzxkkg9', '_log_step_count_steps': 100, '_keep_checkpoint_max': 5, '_session_config': None, '_save_checkpoints_steps': None, '_tf_random_seed': 1, '_keep_checkpoint_every_n_hours': 10000, '_save_checkpoints_secs': 600}


##### ** Train the model for ~1,000 steps. (Later come back to this and train it for more and check for improvement) **

In [40]:
dnn_model.train(input_fn = input_func, steps =1000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/s1/h9x0_mhx4tn1dfstx3w6gvhc0000gn/T/tmp0nzxkkg9/model.ckpt.
INFO:tensorflow:loss = 3.35726e+11, step = 1
INFO:tensorflow:global_step/sec: 364.522
INFO:tensorflow:loss = 9.42712e+10, step = 101 (0.275 sec)
INFO:tensorflow:global_step/sec: 415.75
INFO:tensorflow:loss = 2.08174e+11, step = 201 (0.242 sec)
INFO:tensorflow:global_step/sec: 391.755
INFO:tensorflow:loss = 2.73156e+11, step = 301 (0.258 sec)
INFO:tensorflow:global_step/sec: 366.772
INFO:tensorflow:loss = 3.12854e+11, step = 401 (0.274 sec)
INFO:tensorflow:global_step/sec: 188.541
INFO:tensorflow:loss = 1.35584e+11, step = 501 (0.539 sec)
INFO:tensorflow:global_step/sec: 310.847
INFO:tensorflow:loss = 1.6591e+11, step = 601 (0.313 sec)
INFO:tensorflow:global_step/sec: 381.63
INFO:tensorflow:loss = 1.28589e+11, step = 701 (0.264 sec)
INFO:tensorflow:global_step/sec: 295.387
INFO:tensorflow:loss = 4.19669e+11, step = 801 (0.335 

** Create a prediction input function and then use the .predict method off your estimator model to create a list or predictions on your test data. **

In [43]:
pred_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test,
                                                     batch_size=10,
                                                     num_epochs=1,
                                                     shuffle=False)

In [68]:
pred_gen = dnn_model.predict(pred_input_func)

In [69]:
predictions = list(pred_gen)
predictions

INFO:tensorflow:Restoring parameters from /var/folders/s1/h9x0_mhx4tn1dfstx3w6gvhc0000gn/T/tmp0nzxkkg9/model.ckpt-1000


[{'predictions': array([ 86884.1015625], dtype=float32)},
 {'predictions': array([ 49849.26171875], dtype=float32)},
 {'predictions': array([ 82110.1484375], dtype=float32)},
 {'predictions': array([ 86756.7421875], dtype=float32)},
 {'predictions': array([ 151192.984375], dtype=float32)},
 {'predictions': array([ 203641.15625], dtype=float32)},
 {'predictions': array([ 118167.8828125], dtype=float32)},
 {'predictions': array([ 110004.390625], dtype=float32)},
 {'predictions': array([ 110157.546875], dtype=float32)},
 {'predictions': array([ 5194.12060547], dtype=float32)},
 {'predictions': array([ 135534.203125], dtype=float32)},
 {'predictions': array([ 289658.53125], dtype=float32)},
 {'predictions': array([ 93549.1171875], dtype=float32)},
 {'predictions': array([ 57692.875], dtype=float32)},
 {'predictions': array([ 113504.8046875], dtype=float32)},
 {'predictions': array([ 37854.9375], dtype=float32)},
 {'predictions': array([ 44253.80859375], dtype=float32)},
 {'predictions': ar

** Calculate the RMSE. You should be able to get around 100,000 RMSE (remember that this is in the same units as the label.) Do this manually or use [sklearn.metrics](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html) **

In [72]:
final_preds = []

for pred in predictions:
    
    final_preds.append(pred['predictions'])

In [75]:
final_preds

[array([ 86884.1015625], dtype=float32),
 array([ 49849.26171875], dtype=float32),
 array([ 82110.1484375], dtype=float32),
 array([ 86756.7421875], dtype=float32),
 array([ 151192.984375], dtype=float32),
 array([ 203641.15625], dtype=float32),
 array([ 118167.8828125], dtype=float32),
 array([ 110004.390625], dtype=float32),
 array([ 110157.546875], dtype=float32),
 array([ 5194.12060547], dtype=float32),
 array([ 135534.203125], dtype=float32),
 array([ 289658.53125], dtype=float32),
 array([ 93549.1171875], dtype=float32),
 array([ 57692.875], dtype=float32),
 array([ 113504.8046875], dtype=float32),
 array([ 37854.9375], dtype=float32),
 array([ 44253.80859375], dtype=float32),
 array([ 120291.203125], dtype=float32),
 array([ 177313.578125], dtype=float32),
 array([ 102556.21875], dtype=float32),
 array([ 163897.015625], dtype=float32),
 array([ 368651.59375], dtype=float32),
 array([ 210156.625], dtype=float32),
 array([ 82060.4609375], dtype=float32),
 array([ 161056.890625], d

In [76]:
from sklearn.metrics import mean_squared_error

In [78]:
mean_squared_error(y_test,final_preds)**0.5

162902.44471703595

# Great Job!